package com.techstore;
import android.content.Intent; import android.net.Uri; import android.os.Bundle; import android.text.Editable; import android.text.TextWatcher; import android.widget.Button; import android.widget.EditText; import android.widget.Toast; import androidx.appcompat.app.AppCompatActivity; import androidx.recyclerview.widget.LinearLayoutManager; import androidx.recyclerview.widget.RecyclerView; import androidx.swiperefreshlayout.widget.SwipeRefreshLayout; import com.android.volley.Request; import com.android.volley.toolbox.StringRequest; import com.android.volley.toolbox.Volley; import com.techstore.adapters.AppAdapter; import com.techstore.models.AppModel; import org.json.JSONArray; import org.json.JSONObject; import java.util.ArrayList; import java.util.List;
public class MainActivity extends AppCompatActivity {
    RecyclerView recyclerApps; AppAdapter appAdapter; List<AppModel> fullAppList = new ArrayList<>(); SwipeRefreshLayout swipeRefresh; EditText searchBox; String JSON_URL = "https://pastebin.com/raw/NazABkD4";
    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState); setContentView(R.layout.activity_main);
        recyclerApps = findViewById(R.id.recyclerApps); swipeRefresh = findViewById(R.id.swipeRefresh); searchBox = findViewById(R.id.searchBox); Button btnUpload = findViewById(R.id.btnUpload);
        recyclerApps.setLayoutManager(new LinearLayoutManager(this)); appAdapter = new AppAdapter(this, fullAppList); recyclerApps.setAdapter(appAdapter); fetchAppsOnline(); swipeRefresh.setOnRefreshListener(this::fetchAppsOnline);
        btnUpload.setOnClickListener(v -> { Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://t.me/TechguruStore_bot")); startActivity(intent); });
        searchBox.addTextChangedListener(new TextWatcher() { @Override public void beforeTextChanged(CharSequence s, int start, int count, int after) {} @Override public void onTextChanged(CharSequence s, int start, int before, int count) { List<AppModel> filtered = new ArrayList<>(); for (AppModel app : fullAppList) { if (app.name.toLowerCase().contains(s.toString().toLowerCase())) { filtered.add(app); } } appAdapter.filterList(filtered); } @Override public void afterTextChanged(Editable s) {} });
    }
    private void fetchAppsOnline() {
        swipeRefresh.setRefreshing(true); StringRequest request = new StringRequest(Request.Method.GET, JSON_URL, response -> { try { fullAppList.clear(); JSONArray array = new JSONArray(response); for (int i = 0; i < array.length(); i++) { JSONObject obj = array.getJSONObject(i); ArrayList<String> screens = new ArrayList<>(); if(obj.has("screenshots")) { JSONArray ssArray = obj.getJSONArray("screenshots"); for(int j = 0; j < ssArray.length(); j++) { screens.add(ssArray.getString(j)); } } fullAppList.add(new AppModel( obj.getString("name"), obj.getString("developer"), obj.getString("version"), obj.getString("size"), obj.getString("rating"), obj.getString("icon"), obj.getString("banner"), obj.getString("download"), obj.getString("description"), obj.getString("category"), screens )); } appAdapter.notifyDataSetChanged(); } catch (Exception e) { Toast.makeText(this, "JSON Error!", Toast.LENGTH_SHORT).show(); } swipeRefresh.setRefreshing(false); }, error -> { Toast.makeText(this, "Network Error", Toast.LENGTH_SHORT).show(); swipeRefresh.setRefreshing(false); }); request.setShouldCache(false); Volley.newRequestQueue(this).add(request);
    }
}
